# Generated by Django 4.2.7 on 2025-07-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="timezone_info",
            field=models.JSONField(
                blank=True,
                help_text="JSON containing timezone and location details",
                null=True,
            ),
        ),
    ]
