# Generated by Django 4.2.7 on 2025-07-23 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants", "0004_scrapingbacklogtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="estimated_prep_time",
            field=models.CharField(
                blank=True, help_text="e.g., '15-20 minutes'", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_available_for_cart",
            field=models.BooleanField(
                default=True, help_text="Can users add this item to cart?"
            ),
        ),
        migrations.CreateModel(
            name="UserCart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Special requests or notes"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_carts",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatCartInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_message",
                    models.TextField(help_text="User's message to the chatbot"),
                ),
                ("bot_response", models.TextField(help_text="Chatbot's response")),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("add_item", "Added Item to Cart"),
                            ("remove_item", "Removed Item from Cart"),
                            ("modify_quantity", "Modified Item Quantity"),
                            ("show_menu", "Showed Menu Items"),
                            ("show_cart", "Showed Cart Contents"),
                            ("clear_cart", "Cleared Cart"),
                            ("provide_info", "Provided Information"),
                            ("no_action", "No Action Taken"),
                        ],
                        default="no_action",
                        max_length=50,
                    ),
                ),
                (
                    "items_affected",
                    models.JSONField(
                        default=list,
                        help_text="List of menu item IDs affected by this interaction",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, help_text="Chat session identifier", max_length=100
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_interactions",
                        to="restaurants.usercart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_cart_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True, help_text="Customizations or special requests"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurants.usercart",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="restaurants.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usercart",
            index=models.Index(
                fields=["user", "is_active"], name="restaurants_user_id_ee9c08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercart",
            index=models.Index(
                fields=["restaurant", "is_active"],
                name="restaurants_restaur_fb9f71_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercart",
            unique_together={("user", "restaurant", "is_active")},
        ),
        migrations.AddIndex(
            model_name="chatcartinteraction",
            index=models.Index(
                fields=["user", "created_at"], name="restaurants_user_id_93d021_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatcartinteraction",
            index=models.Index(
                fields=["session_id"], name="restaurants_session_2242ff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "menu_item")},
        ),
    ]
