# Generated by Django 4.2.7 on 2025-07-20 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_restaurant_timezone_info"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoriteRestaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("to_visit", "Want to Visit"),
                            ("visited", "Visited & Loved"),
                            ("special_occasion", "Special Occasions"),
                            ("business_dining", "Business Dining"),
                            ("romantic", "Romantic Dinners"),
                            ("family", "Family-Friendly"),
                            ("quick_bite", "Quick Bites"),
                        ],
                        default="to_visit",
                        max_length=50,
                    ),
                ),
                (
                    "personal_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 Stars"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        help_text="Personal rating (1-5 stars)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this restaurant"
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        blank=True, help_text="Date of visit (if visited)", null=True
                    ),
                ),
                (
                    "recommended_dishes",
                    models.JSONField(
                        blank=True, default=list, help_text="List of recommended dishes"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_restaurants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Restaurant",
                "verbose_name_plural": "Favorite Restaurants",
                "ordering": ["-added_at"],
                "unique_together": {("user", "restaurant")},
            },
        ),
        migrations.CreateModel(
            name="UserChatHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversation_id", models.CharField(db_index=True, max_length=100)),
                ("session_start", models.DateTimeField(auto_now_add=True)),
                ("session_end", models.DateTimeField(blank=True, null=True)),
                (
                    "topics_discussed",
                    models.JSONField(
                        default=list,
                        help_text="Main topics discussed in this conversation",
                    ),
                ),
                (
                    "preferences_learned",
                    models.JSONField(
                        default=dict,
                        help_text="User preferences discovered during conversation",
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 Stars"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        help_text="User's satisfaction with the conversation",
                        null=True,
                    ),
                ),
                (
                    "restaurants_mentioned",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restaurants discussed in this conversation",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat History",
                "verbose_name_plural": "Chat Histories",
                "ordering": ["-session_start"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]