# Generated by Django 4.2.7 on 2025-07-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_scrapingbacklogtask"),
        ("accounts", "0002_additional_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfavoriterestaurant",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_favorites",
                to="restaurants.restaurant",
            ),
        ),
    ]
